#!/usr/bin/env node
// scripts/build-esm.js
// Post-process the CJS dist to also produce a minimal ESM bundle
// by re-exporting from the compiled output. This keeps the build
// zero-dependency (no Rollup / esbuild required).

const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "..", "dist");

// Read the compiled CJS index and rewrite module syntax to ESM
// For a zero-dep build we just emit a thin ESM re-export wrapper.
const esmContent = `// ESM entry — generated by scripts/build-esm.js
export { normalize, inferSchema } from "./index.js";
export * from "./types.js";
`;

fs.writeFileSync(path.join(distDir, "index.esm.js"), esmContent, "utf8");

console.log("✓  ESM wrapper written to dist/index.esm.js");
